kind: Deployment
apiVersion: apps/v1
metadata:
  name: daodns
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daodns
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: daodns
      annotations:
        ipam.spidernet.io/ippools: >-
          [{"interface":"net1","ipv4":["default-v4-ippool"],"ipv6":["default-v6-ippool"]}]
        k8s.v1.cni.cncf.io/networks: kube-system/macvlan-overlay-vlan0
        v1.multus-cni.io/default-network: kube-system/calico
    spec:
      containers:
        - name: container-1
          image: daocloud.io/daocloud/dao-2048:latest
          resources:
            limits:
              cpu: 100m
              memory: 51Mi
            requests:
              cpu: 100m
              memory: 51Mi
          lifecycle: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      dnsConfig: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
