apiVersion: v1
kind: Service
metadata:
  name: daodns-service
  namespace: default
  labels:
    app: daodns
spec:
  ports:
    - name: tcp-80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: daodns
