kind: Deployment
apiVersion: apps/v1
metadata:
  name: dnstools
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnstools
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dnstools
    spec:
      containers:
        - name: container-1
          image: infoblox/dnstools:latest
          command:
            - sleep
          args:
            - '86400'          
          resources:
            limits:
              cpu: 100m
              memory: 51Mi
            requests:
              cpu: 100m
              memory: 51Mi
          lifecycle: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      dnsConfig: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600